# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
# Always build releases and on pushed tags also publish to PyPI
name: Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-python-package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -l dist

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get image tag
        id: image
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs\/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: consideratio/discourse-sso-oidc-bridge:${{ steps.image.outputs.tag }}

      - name: docker run
        run: |
          container=$(docker run -d --rm consideratio/discourse-sso-oidc-bridge:${{ steps.image.outputs.tag }})
          sleep 5
          docker stop $container

      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: consideratio/discourse-sso-oidc-bridge:${{ steps.image.outputs.tag }}
